### ISSUE TITLE
Can't update user information

### ISSUE THREAD

**Issue by zmanion** [CERTCC/cveClient#11]
A CNA/org admin should be able to update any user information. When trying to update last name, second dialog has blue "Add User" button (should perhaps be "Update User"), edit name, "Update User" button now appears (but "Add User" remains, remove it), click "Update User", get BAD_INPUT error.

**Comment by sei-vsarvepalli** [comment]
Hello @zmanion 

The dev branch with v.1.0.15 runs at democert.org/cveClient has this issue fixed. Can you check to see if this is fixed.  The buttons visibility issue is fixed.  If you still get the BAD_INPUT error, can you provide full error from Javascript Console or a screenshot if there is more information provided in the BAD_INPUT case.

Thanks

**Comment by zmanion** [comment]
Using democert.org, still can't change first or last name or email address (user name). Was able to change last name when *also* changing ADMIN role.

**Comment by zmanion** [comment]
Attempt to change name.Last, gets a 400, maybe because active_roles is empty?
```
cveClientlib.js:142          PUT https://cveawg-test.mitre.org/api/org/Paleozoic/user/test@example.com?name.last=Five&active_roles=&name.first=Terry 400
rfetch @ cveClientlib.js:142
(anonymous) @ cveInterface.js?version=2022081915:1259
Promise.then (async)
(anonymous) @ cveInterface.js?version=2022081915:1257
Promise.then (async)
client.rfetch @ cveInterface.js?version=2022081915:1253
putjson @ cveClientlib.js:119
updateuser @ cveClientlib.js:86
do_update_user @ cveInterface.js?version=2022081915:949
update_user @ cveInterface.js?version=2022081915:942
onclick @ (index):152
```

**Comment by zmanion** [comment]
This works, updating name.first, no active_roles parameter, this user is ADMIN before the request.
```
cveClientlib.js:142 Fetch finished loading: PUT "https://cveawg-test.mitre.org/api/org/Paleozoic/user/zmanion@protonmail.com?name.first=Arthur&name.last=Manion".
rfetch @ cveClientlib.js:142
(anonymous) @ cveInterface.js?version=2022081915:1259
Promise.then (async)
(anonymous) @ cveInterface.js?version=2022081915:1257
Promise.then (async)
client.rfetch @ cveInterface.js?version=2022081915:1253
putjson @ cveClientlib.js:119
updateuser @ cveClientlib.js:86
do_update_user @ cveInterface.js?version=2022081915:949
update_user @ cveInterface.js?version=2022081915:942
onclick @ (index):152
```

**Comment by sei-vsarvepalli** [comment]
> Attempt to change name.Last, gets a 400, maybe because active_roles is empty?
> 
> ```
> cveClientlib.js:142          PUT https://cveawg-test.mitre.org/api/org/Paleozoic/user/test@example.com?name.last=Five&active_roles=&name.first=Terry 400
> rfetch @ cveClientlib.js:142
> (anonymous) @ cveInterface.js?version=2022081915:1259
> Promise.then (async)
> (anonymous) @ cveInterface.js?version=2022081915:1257
> Promise.then (async)
> client.rfetch @ cveInterface.js?version=2022081915:1253
> putjson @ cveClientlib.js:119
> updateuser @ cveClientlib.js:86
> do_update_user @ cveInterface.js?version=2022081915:949
> update_user @ cveInterface.js?version=2022081915:942
> onclick @ (index):152
> ```

Very strange indeed. I am not able to reproduce it, is your browser Chrome? The active_roles field should be emptied before submission to PUT methods by default. Anyway I have double verified that empty fields are removed in the dev version at https://democert.org/cveClient/ 

Can you please give it one more try? 

Thanks
Vijay

**Comment by zmanion** [comment]
Chrome, incognito window, democert.org, still cannot update a non-admin user. Sends this URL:

https://cveawg-test.mitre.org/api/org/Paleozoic/user/foo@example.com?name.first=Fuzz&active_roles=&name.last=Bar

```
art@plank ~
$ curl -H 'CVE-API-ORG: Paleozoic' -H 'CVE-API-USER: zmanion@protonmail.com' -H 'CVE-API-KEY: 1234' -X PUT 'https://cveawg-test.mitre.org/api/org/Paleozoic/user/foo@example.com?name.first=Fuzz&active_roles=&name.last=Bart'
{"error":"BAD_INPUT","message":"Parameters were invalid","details":[{"msg":"'active_roles' is not a valid parameter name.","param":"","location":"query"}]}
art@plank ~
$ curl -H 'CVE-API-ORG: Paleozoic' -H 'CVE-API-USER: zmanion@protonmail.com' -H 'CVE-API-KEY: 1234' -X PUT 'https://cveawg-test.mitre.org/api/org/Paleozoic/user/foo@example.com?name.first=Fuzz&name.last=Bart'
{"message":"foo@example.com was successfully updated.","updated":{"username":"foo@example.com","org_UUID":"77e550a0-813d-44aa-8a55-a59814101335","time":{"created":"2022-09-26T20:17:13.093Z","modified":"2022-10-10T21:02:38.976Z"},"UUID":"99c9aa43-faea-4b3a-a5cc-a2aad1106910","active":true,"authority":{"active_roles":[]},"name":{"first":"Fuzz","last":"Bart","middle":"","suffix":""}}}
```

**Comment by zmanion** [comment]
Can(!) change user info when running local web server on main branch.

**Comment by zmanion** [comment]
https://certcc.github.io/cveClient/ also works.

**Comment by sei-vsarvepalli** [comment]
> Chrome, incognito window, democert.org, still cannot update a non-admin user. Sends this URL:
> 
> https://cveawg-test.mitre.org/api/org/Paleozoic/user/foo@example.com?name.first=Fuzz&active_roles=&name.last=Bar
> 
> ```
> art@plank ~
> $ curl -H 'CVE-API-ORG: Paleozoic' -H 'CVE-API-USER: zmanion@protonmail.com' -H 'CVE-API-KEY: 1234' -X PUT 'https://cveawg-test.mitre.org/api/org/Paleozoic/user/foo@example.com?name.first=Fuzz&active_roles=&name.last=Bart'
> {"error":"BAD_INPUT","message":"Parameters were invalid","details":[{"msg":"'active_roles' is not a valid parameter name.","param":"","location":"query"}]}
> art@plank ~
> $ curl -H 'CVE-API-ORG: Paleozoic' -H 'CVE-API-USER: zmanion@protonmail.com' -H 'CVE-API-KEY: 1234' -X PUT 'https://cveawg-test.mitre.org/api/org/Paleozoic/user/foo@example.com?name.first=Fuzz&name.last=Bart'
> {"message":"foo@example.com was successfully updated.","updated":{"username":"foo@example.com","org_UUID":"77e550a0-813d-44aa-8a55-a59814101335","time":{"created":"2022-09-26T20:17:13.093Z","modified":"2022-10-10T21:02:38.976Z"},"UUID":"99c9aa43-faea-4b3a-a5cc-a2aad1106910","active":true,"authority":{"active_roles":[]},"name":{"first":"Fuzz","last":"Bart","middle":"","suffix":""}}}
> ```

A slight chance when you are on Chrome Private mode, you are still seeing a Cached version. The demo server sends a pretty long cache hoping to E-Tag to verify the status of the page. Anyway you can try https://democert.org/cveClient/?rand=11 or some strange query string to force browser ignore the cache and pull down the main page which will force update of all the Client libs.  To verify the latest version is being used, if you go to JavaScript Console and check `_version` should be `1.0.14` and `client._version` should be `1.0.13`

**Comment by zmanion** [comment]
All working now, did the query string trick, confirmed versions, thanks.
